# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://mhbakalar.github.io/peptide_ms_stability/"

git_url = "https://github.com/mhbakalar/peptide_ms_stability/tree/main/"

def custom_doc_links(name): return None
